#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Copy the current /etc/hosts file to the user's home directory
cp /etc/hosts ~/hosts.new

# Add an entry for localhost to the new hosts file
echo "127.0.0.2		localhost" > ~/hosts.new

# Add an entry for facebook.com to the new hosts file
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts file with the new one
cp -f ~/hosts.new /etc/hosts
